const CONFIG = {
  ATELIER_TITLE: process.env.NEXT_PUBLIC_ATELIER_TITLE || 'Atelier OS',
  ATELIER_SUBTITLE:
    process.env.NEXT_PUBLIC_ATELIER_SUBTITLE ||
    'PERSONAL BLOG / DIGITAL GARDEN',
  ATELIER_HERO_EYEBROW:
    process.env.NEXT_PUBLIC_ATELIER_HERO_EYEBROW || 'LIVE KNOWLEDGE FIELD',
  ATELIER_HERO_TITLE:
    process.env.NEXT_PUBLIC_ATELIER_HERO_TITLE || '把博客做成\n个人知识操作台',
  ATELIER_HERO_DESCRIPTION:
    process.env.NEXT_PUBLIC_ATELIER_HERO_DESCRIPTION ||
    '文章不是列表，是持续生长的主题、项目、问题和决策轨迹。',
  ATELIER_PRIMARY_CTA:
    process.env.NEXT_PUBLIC_ATELIER_PRIMARY_CTA || 'ENTER NOTES',
  ATELIER_SECONDARY_CTA:
    process.env.NEXT_PUBLIC_ATELIER_SECONDARY_CTA || 'VIEW MAP',
  ATELIER_SHOW_READING_PROGRESS:
    process.env.NEXT_PUBLIC_ATELIER_SHOW_READING_PROGRESS || true,
  ATELIER_POST_AD_ENABLE:
    process.env.NEXT_PUBLIC_ATELIER_POST_AD_ENABLE || false,
  ATELIER_MENU_CATEGORY: process.env.NEXT_PUBLIC_ATELIER_MENU_CATEGORY || true,
  ATELIER_MENU_TAG: process.env.NEXT_PUBLIC_ATELIER_MENU_TAG || true,
  ATELIER_MENU_ARCHIVE: process.env.NEXT_PUBLIC_ATELIER_MENU_ARCHIVE || true
}

export default CONFIG
