const CONFIG = {
  CYBERPUNK_HOME_POST_TWO_COLS: true,
  CYBERPUNK_LOADING_COVER: true,

  CYBERPUNK_HOME_BANNER_ENABLE: true,
  CYBERPUNK_SITE_CREATE_TIME: '2021-05-12',

  CYBERPUNK_NOTICE_BAR: [
    { title: '欢迎来到赛博空间', url: '' }
  ],

  CYBERPUNK_HERO_REVERSE: false,
  CYBERPUNK_HERO_BODY_REVERSE: false,

  CYBERPUNK_HERO_TITLE_1: 'NEURAL',
  CYBERPUNK_HERO_TITLE_2: 'NETWORK',
  CYBERPUNK_HERO_TITLE_3: 'CYBERPUNK',
  CYBERPUNK_HERO_TITLE_4: '2077',
  CYBERPUNK_HERO_TITLE_5: '数据驱动未来 / DATA DRIVES THE FUTURE',
  CYBERPUNK_HERO_TITLE_LINK: '',

  CYBERPUNK_HERO_CATEGORY_1: { title: '系统日志', url: '/category/技术' },
  CYBERPUNK_HERO_CATEGORY_2: { title: '数据流', url: '/category/生活' },
  CYBERPUNK_HERO_CATEGORY_3: { title: '神经接口', url: '/archive' },

  CYBERPUNK_HERO_RECOMMEND_POST_TAG: '',
  CYBERPUNK_HERO_RECOMMEND_POST_SORT_BY_UPDATE_TIME: false,

  CYBERPUNK_INFOCARD_GREETINGS: [
    '你好，网络行者',
    '欢迎接入赛博空间',
    '数据流正在同步...',
    '神经链接已建立',
    '系统状态：在线',
    '防火墙：激活',
    '加密协议：启用'
  ],

  CYBERPUNK_INFO_CARD_URL1: '/about',
  CYBERPUNK_INFO_CARD_ICON1: 'fas fa-user-cog',
  CYBERPUNK_INFO_CARD_URL2: 'https://github.com',
  CYBERPUNK_INFO_CARD_ICON2: 'fab fa-github',
  CYBERPUNK_INFO_CARD_URL3: '',
  CYBERPUNK_INFO_CARD_TEXT3: '了解更多',

  CYBERPUNK_GROUP_ICONS: [],

  CYBERPUNK_SOCIAL_CARD: false,
  CYBERPUNK_SOCIAL_CARD_TITLE_1: '连接网络',
  CYBERPUNK_SOCIAL_CARD_TITLE_2: '加入我们的数据流',
  CYBERPUNK_SOCIAL_CARD_TITLE_3: '点击接入',
  CYBERPUNK_SOCIAL_CARD_URL: '',

  CYBERPUNK_POST_COUNT_TITLE: '数据节点:',
  CYBERPUNK_SITE_TIME_TITLE: '运行周期:',
  CYBERPUNK_SITE_VISIT_TITLE: '访问流量:',
  CYBERPUNK_SITE_VISITOR_TITLE: '连接数:',

  CYBERPUNK_MENU_INDEX: true,
  CYBERPUNK_MENU_CATEGORY: true,
  CYBERPUNK_MENU_TAG: true,
  CYBERPUNK_MENU_ARCHIVE: true,
  CYBERPUNK_MENU_SEARCH: true,

  CYBERPUNK_POST_LIST_COVER: true,
  CYBERPUNK_POST_LIST_COVER_HOVER_ENLARGE: true,
  CYBERPUNK_POST_LIST_COVER_DEFAULT: true,
  CYBERPUNK_POST_LIST_SUMMARY: true,
  CYBERPUNK_POST_LIST_PREVIEW: false,
  CYBERPUNK_POST_LIST_IMG_CROSSOVER: true,

  CYBERPUNK_ARTICLE_ADJACENT: true,
  CYBERPUNK_ARTICLE_COPYRIGHT: true,
  CYBERPUNK_ARTICLE_NOT_BY_AI: false,
  CYBERPUNK_ARTICLE_RECOMMEND: true,

  CYBERPUNK_WIDGET_LATEST_POSTS: true,
  CYBERPUNK_WIDGET_ANALYTICS: false,
  CYBERPUNK_WIDGET_TO_TOP: true,
  CYBERPUNK_WIDGET_TO_COMMENT: true,
  CYBERPUNK_WIDGET_DARK_MODE: true,
  CYBERPUNK_WIDGET_TOC: true,

  CYBERPUNK_GLOW_EFFECT: true,
  CYBERPUNK_GLITCH_EFFECT: true,
  CYBERPUNK_SCANLINE_EFFECT: true,
  CYBERPUNK_NEON_BORDER: true
}
export default CONFIG
